### ISSUE TITLE
Take an attributed string with initial attributes

### ISSUE THREAD

**Issue by Cinamonas** [daltoniam/bumblebee#1]
At the moment, Bumblebee can only process `String`s. But it would also make sense to pass it an `NSAttributedString` with initial attributes.

**Comment by daltoniam** [comment]
At what point would it make sense to pass that in? In the `process()` method? Maybe I am missing the use case, but I don't see at what point the `NSAttributedString` would be passed in.

**Comment by Cinamonas** [comment]
Yes, the `process:` method should be able to take an attributed string to add _additional_ attributes at specific ranges (depending on patterns).

Use-case: I have an attributed string with specific foreground color, font and paragraph styling and would like to set bold font for its substring with Bumblebee.

I believe it is potentially a very common use case, don't you agree?

**Comment by daltoniam** [comment]
Agreed that makes sense. Thanks. Sounds like a good feature to add.
