### ISSUE TITLE
Use GitHub tags to identify features

### ISSUE THREAD

**Issue by ghost** [daltoniam/bumblebee#10]
Here is an example:
<img width="461" alt="capture d ecran 2015-10-24 a 10 21 49" src="https://cloud.githubusercontent.com/assets/385357/10709726/16e2b002-7a39-11e5-886a-f0f7cdad1836.png">

**Comment by daltoniam** [comment]
I haven't looked into adding SVG badges like this. I will look into as time permits. PR welcomed if you already have done it.

**Comment by ghost** [comment]
Ok, here is the result of my search:
- http://shields.io
- https://github.com/drnic/github-shields
