### ISSUE TITLE
Example does not work on Swift2

### ISSUE THREAD

**Issue by ghost** [daltoniam/bumblebee#12]
Compilation error using `advance`:  
`let replace = pattern[advance(pattern.startIndex, 1)...advance(pattern.endIndex, -2)]
`

Error is:  
 `'advance' is unavailable: call the 'advancedBy(n)' method on the index`

**Comment by ghost** [comment]
`let replace = pattern[advance(pattern.startIndex, 1)...advance(pattern.endIndex, -2)]`

Replace above line by the one below:
`let replace = pattern[pattern.startIndex.advancedBy(1)...pattern.endIndex.advancedBy(-2)]`

**Comment by daltoniam** [comment]
Fixed. Thanks.
