### ISSUE TITLE
How to manage default attributes?

### ISSUE THREAD

**Issue by ghost** [daltoniam/bumblebee#13]
Current example transform raw text to `NSAttributedString` for few markdown patters:
- emphasized text,`*?*`
- important text, `_*_`
- image pattern,`![?](?)`

But how to apply default formatting to overall text?

**Comment by ghost** [comment]
One solution is to add default attributes data as parameter to `init` then apply them first at the end before _adding_ generated attributes by replacing `setAttributes` by `addAttributes`.

``` swift
public func process(srcText: String, attrs:[String : AnyObject]) -> NSAttributedString {

...

 // we have our patterns, let's build a stylized string

 // 1. Apply default attributes
 let attributedText = NSMutableAttributedString(string:text, attributes:attrs)

 // 2. Add attributes brought by markdown
 for pattern in collect {
     attributedText.addAttributes(pattern.attrs!, range: NSMakeRange(pattern.start, pattern.length))
 }

}

```

**Comment by ghost** [comment]
Sorry, same as https://github.com/daltoniam/bumblebee/issues/1

**Comment by ghost** [comment]
Oups, closed by mistake.

**Comment by daltoniam** [comment]
`1.0.1` released. See README:

``` swift
let defaultAttrs = [NSFontAttributeName: UIFont.systemFontOfSize(18)] //default attributes to apply
let attrString = bee.process(rawText,attributes: defaultAttrs) //attributes can be omited if unneeded
```
