### ISSUE TITLE
5 errors when building

### ISSUE THREAD

**Issue by forjoyilive** [daltoniam/bumblebee#18]
<img width="1148" alt="screen shot 2016-03-05 at 6 54 36 pm" src="https://cloud.githubusercontent.com/assets/2933255/13552020/dbabe70e-e303-11e5-8410-516f48d4b47f.png">

When I build, I get these errors, shown here. It could be that I'm doing something wrong.

Any ideas? I'm using Xcode 7.3 beta.

**Comment by daltoniam** [comment]
I believe that is because it is using an old build of bumblebee. Are you using the latest code in master or the 1.0.1 tag?

**Comment by forjoyilive** [comment]
Aha, that's it. Looks like the code is 0.9.2.

I just copied and pasted the Cocoapods configuration in the readme without thinking.

**Comment by daltoniam** [comment]
ah ok, I should probably update that :grin:

**Comment by forjoyilive** [comment]
Works great now, thanks.
