### ISSUE TITLE
Use of unresolved identifier 'advancedBy'

### ISSUE THREAD

**Issue by mengheangrat** [daltoniam/bumblebee#19]
Use of unresolved identifier 'advancedBy'

**Comment by daltoniam** [comment]
You are probably using an old version of Swift. `advancedBy` replaced `advance` in Swift 2. I would recommend upgrading your installed version of Swift/xCode or use the 0.9.2 tag which is built for Swift 1.2.

**Comment by mengheangrat** [comment]
My xCode 7.2 , but it still got error "Use of unresolved identifier 'advancedBy' "

**Comment by daltoniam** [comment]
Alright, can you provide more details then? I haven't seen and can't reproduce that error outside of an old xCode install.

**Comment by DimDL** [comment]
I think the user is talking about the sample code in the README, which doesn't compile out of the box if you copy/paste it. `advancedBy(pattern.startIndex, 1)` simply needs to be changed to `pattern.startIndex.advancedBy(1)`

**Comment by mengheangrat** [comment]
Hello guys do you have any sample for new version, coz I am new dev with Swift.

`bee.add("_?_", recursive: false) { (pattern: String, text: String, start: Int) -> (String, [NSObject : AnyObject]?) in
            let replace = pattern.startIndex.advancedBy(1)...pattern.startIndex.advancedBy(2)
            return (replace,[NSFontAttributeName: UIFont.boldSystemFontOfSize(17)])
        }`
now I got error "Cannot convert return expression of type 'Range<Index>' (aka 'Range<String.CharacterView.Index>') to return type 'String' "
Thank for your help.

**Comment by mengheangrat** [comment]
Now I found more issue 'Skeets' required `SwiftHTTP (~> 0.9.5)` but  `SwiftHTTP (~> 0.9.5)` contain error in swift 2. We need `SwiftHTTP (1.0.4)`

**Comment by daltoniam** [comment]
ah ok. Yeah I hadn't updated the README that is done now. `advanceBy` is not a method call of an `Index` instead of its own function. It should be resolved now. Thanks for the report.

P.S. I haven't had the time to update Skeets, so please use a different image library in the mean time.
