### ISSUE TITLE
If multiple patterns are matched, only last pattern's attributes are added

### ISSUE THREAD

**Issue by Cinamonas** [daltoniam/bumblebee#2]
For example: `[*foo*](c:FF0000)` matches color (`[?](c:?)`) and bold font (`*?*`) patterns, but it only receives color attribute.

There's a workaround, but it ain't pretty.

**Comment by daltoniam** [comment]
true, currently it doesn't support compounded attributes. I agree that would be a cool addition/enhancement.

**Comment by daltoniam** [comment]
`1.0.1` has been released which I believe should address this. Thanks.
