### ISSUE TITLE
image pattern 

### ISSUE THREAD

**Issue by mengheangrat** [daltoniam/bumblebee#20]
fatal error: can not decrement startIndex
`let url = pattern.startIndex.advancedBy(1)..<pattern.startIndex.advancedBy(-1)`

**Comment by daltoniam** [comment]
Can't go backwards from the start :smile:. That should be `endIndex`. Should be correct in the README.

```
let url = pattern.startIndex.advancedBy(1)..<pattern.endIndex.advancedBy(-1)
```
