### ISSUE TITLE
crash on the second bold word 

### ISSUE THREAD

**Issue by Sianay** [daltoniam/bumblebee#21]
I have a sentence with two words that I want to put in bold but it crashes when matching the second one

here is my bold pattern : 

``` swift
//the bold pattern
bee.add("**?**", recursive: false) { (pattern: String, text: String, start: Int) -> (String, [NSObject : AnyObject]?) in
    let replace = pattern[pattern.startIndex.advancedBy(2)..<pattern.endIndex.advancedBy(-2)]
    return (replace, [NSFontAttributeName: UIFont.boldSystemFontOfSize(13)])
}
```

Here is the stack with the original sentence :  

![capture d ecran 2016-03-24 a 15 18 19](https://cloud.githubusercontent.com/assets/1273735/14019581/c18acdf2-f1d3-11e5-99d9-0ffc40c1cdf4.png)

as you see index is not correct for the second word so it may explain the crash

**Comment by daltoniam** [comment]
ah interesting, that is less than ideal. I will try and debug when time permits. If you find the source of the problem before me a PR is welcomed.

**Comment by daltoniam** [comment]
I completely refactor and updated Bumbleebee to Swift 4. This should no longer be an issue with the version 2.0.0 update/refactor.
