### ISSUE TITLE
Swift 3 ?

### ISSUE THREAD

**Issue by AlexZd** [daltoniam/bumblebee#24]
Hello! Any plan to update to Swift 3?

**Comment by daltoniam** [comment]
I plan to, just haven't had the time yet 😄. PRs welcomed.

**Comment by AlexZd** [comment]
[PR](https://github.com/daltoniam/bumblebee/pull/25) created

**Comment by daltoniam** [comment]
Took me forever, but updated and completely refactored for Swift 4!
