### ISSUE TITLE
Improve Carthage support

### ISSUE THREAD

**Issue by ghost** [daltoniam/bumblebee#8]
In order to determine which version is for `cart file` user must search into files. I found the version number in the `.podspec` file!

`github "daltoniam/bumblebee" >= 0.9`

**Comment by daltoniam** [comment]
I will add a CHANGELOG/README update going forward to help with this, but you can just check the tags to see the latest version:
![screen shot 2015-10-22 at 10 05 38 am](https://cloud.githubusercontent.com/assets/905059/10672371/840affc2-78a4-11e5-8043-7da85ee3a437.png)

**Comment by ghost** [comment]
Thanks
